#!/usr/bin/env python3
###############################################################################
# download-fonts.py  -  Trogir Insider
#
# Downloads the Google Fonts used by the site (Fraunces + Inter) to a local
# ./fonts folder and writes ./fonts/fonts.css that points to the local files.
# After running this, no data is sent to Google when the site loads its fonts.
#
# The pages already link to  fonts/fonts.css  - this script just creates it.
#
# RUN (from your project folder):
#     python download-fonts.py        (Windows)
#     python3 download-fonts.py       (macOS/Linux)
###############################################################################

import os
import re
import urllib.parse
import urllib.request

CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;"
           "0,9..144,500;1,9..144,300&family=Inter:wght@300;400;500;600&display=swap")

OUT = "fonts"
# A modern browser User-Agent so Google returns the small, modern .woff2 files
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main():
    os.makedirs(OUT, exist_ok=True)
    print("Fetching font stylesheet from Google...")
    css = get(CSS_URL).decode("utf-8")

    urls = sorted(set(re.findall(r'https://fonts\.gstatic\.com/[^)\'"]+\.woff2', css)))
    if not urls:
        print("! No .woff2 URLs found. Check your internet connection and try again.")
        return

    print("Found %d font files. Downloading..." % len(urls))
    for url in urls:
        name = os.path.basename(urllib.parse.urlparse(url).path)
        if not name.endswith(".woff2"):
            name += ".woff2"
        try:
            data = get(url)
            with open(os.path.join(OUT, name), "wb") as f:
                f.write(data)
            css = css.replace(url, name)   # point the CSS at the local file
            print("   [ok] %s" % name)
        except Exception as e:
            print("   ! failed %s (%s)" % (name, e))

    with open(os.path.join(OUT, "fonts.css"), "w", encoding="utf-8") as f:
        f.write("/* Self-hosted fonts - generated by download-fonts.py */\n")
        f.write(css)

    print("\nDone. Created ./%s/fonts.css and %d .woff2 files." % (OUT, len(urls)))
    print("The site already links to fonts/fonts.css - just commit the fonts folder.")


if __name__ == "__main__":
    main()
